# Generated by Django 4.2.4 on 2023-08-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_customuser_full_name_alter_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department',
            field=models.CharField(default='系统', max_length=100),
        ),
    ]
