# Generated by Django 4.2.4 on 2023-08-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_department_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(default='系统', max_length=100),
        ),
    ]
