# Generated by Django 4.2.4 on 2023-08-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(max_length=100),
        ),
    ]
