# Generated by Django 4.2.4 on 2023-08-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_management', '0002_rename_upload_date_document_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.CharField(max_length=100),
        ),
    ]
