# Generated by Django 4.2.4 on 2023-08-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_management', '0006_previewrequest_approved_by_previewrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contract_amount_with_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='contract_amount_without_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='contract_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='contract_signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
