# Generated by Django 4.2.4 on 2023-08-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_management', '0007_document_contract_amount_with_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contract_category',
            field=models.CharField(choices=[('paper', '纸质文档'), ('electronic', '电子文档')], default='paper', max_length=20),
        ),
    ]
