# Generated by Django 4.2.4 on 2023-08-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_management', '0008_document_contract_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
