# Generated by Django 4.2.4 on 2023-08-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_management', '0009_paymentterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doc_management.paymentterm'),
        ),
    ]
